import { describe, expect, it } from "vitest";
import { CliUsageError } from "../src/cli/parse.js";
import {
  CLI_EXIT_CODES,
  ERROR_EXIT_CODES,
  exitCodeForError,
  type CliExitCode
} from "../src/cli/exit-codes.js";
import { MiftahError, type MiftahErrorCode } from "../src/utils/errors.js";

const expectedErrorExitCodes: Record<MiftahErrorCode, CliExitCode> = {
  CONFIG_NOT_FOUND: CLI_EXIT_CODES.config,
  CONFIG_INVALID_JSON: CLI_EXIT_CODES.config,
  CONFIG_SCHEMA_INVALID: CLI_EXIT_CODES.config,
  CONFIG_UNKNOWN_OPTION: CLI_EXIT_CODES.config,
  UNSUPPORTED_CONFIG_VERSION: CLI_EXIT_CODES.config,
  CONFIG_MIGRATION_CONFLICT: CLI_EXIT_CODES.config,
  CONFIG_MIGRATION_BACKUP_EXISTS: CLI_EXIT_CODES.config,
  CONFIG_MIGRATION_WRITE_FAILED: CLI_EXIT_CODES.config,
  CONFIG_ALREADY_EXISTS: CLI_EXIT_CODES.config,
  CONFIG_CREATE_FAILED: CLI_EXIT_CODES.config,
  DEFAULT_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  POLICY_NOT_FOUND: CLI_EXIT_CODES.config,
  ROUTING_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  LOCK_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  UPSTREAM_NOT_FOUND: CLI_EXIT_CODES.config,
  UNSUPPORTED_CONFIG_OPTION: CLI_EXIT_CODES.config,
  PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  PROFILE_SWITCH_DISABLED: CLI_EXIT_CODES.config,
  PROFILE_SWITCH_CONFIRMATION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_SELECTION_STALE: CLI_EXIT_CODES.policy,
  PROFILE_LOCKING_DISABLED: CLI_EXIT_CODES.policy,
  PROFILE_LOCKED: CLI_EXIT_CODES.policy,
  PROFILE_LEASE_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_LEASE_EXPIRED: CLI_EXIT_CODES.policy,
  PROFILE_SELECTION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_IDENTITY_SELECTION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_IDENTITY_CONFIRMATION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_STATE_WRITE_FAILED: CLI_EXIT_CODES.config,
  SECRET_ENV_MISSING: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_FAILED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_UNAVAILABLE: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_TIMEOUT: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_CANCELLED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_LOCKED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_NONINTERACTIVE: CLI_EXIT_CODES.secret,
  SECRET_REFERENCE_MALFORMED: CLI_EXIT_CODES.secret,
  SECRET_ITEM_MISSING: CLI_EXIT_CODES.secret,
  PLUGIN_API_INCOMPATIBLE: CLI_EXIT_CODES.config,
  UPSTREAM_START_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_INIT_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_SHUTDOWN_TIMEOUT: CLI_EXIT_CODES.upstream,
  UPSTREAM_CONCURRENCY_LIMIT: CLI_EXIT_CODES.upstream,
  UPSTREAM_RESTART_LIMIT_EXCEEDED: CLI_EXIT_CODES.upstream,
  UPSTREAM_TOOL_LIST_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_DISCOVERY_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_CALL_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_HTTP_ERROR: CLI_EXIT_CODES.upstream,
  UPSTREAM_PROTOCOL_ERROR: CLI_EXIT_CODES.upstream,
  AUDIT_WRITE_FAILED: CLI_EXIT_CODES.operation,
  UPSTREAM_SELECTION_AMBIGUOUS: CLI_EXIT_CODES.upstream,
  ROUTING_AMBIGUOUS: CLI_EXIT_CODES.policy,
  ROUTING_BLOCKED: CLI_EXIT_CODES.policy,
  ROUTING_PLUGIN_FAILED: CLI_EXIT_CODES.policy,
  ROUTING_PLUGIN_TIMEOUT: CLI_EXIT_CODES.policy,
  ROUTING_PLUGIN_CANCELLED: CLI_EXIT_CODES.policy,
  POLICY_BLOCKED: CLI_EXIT_CODES.policy,
  POLICY_CONFIRMATION_REQUIRED: CLI_EXIT_CODES.policy,
  APPROVAL_DELEGATION_DISABLED: CLI_EXIT_CODES.policy,
  APPROVAL_MECHANISM_MISMATCH: CLI_EXIT_CODES.policy,
  APPROVAL_INVALID: CLI_EXIT_CODES.policy,
  APPROVAL_EXPIRED: CLI_EXIT_CODES.policy,
  APPROVAL_NOT_PENDING: CLI_EXIT_CODES.policy,
  APPROVAL_LIMIT_EXCEEDED: CLI_EXIT_CODES.policy,
  IDENTITY_NOT_CONFIGURED: CLI_EXIT_CODES.policy,
  IDENTITY_MISMATCH: CLI_EXIT_CODES.policy,
  IDENTITY_BINDING_UNAVAILABLE: CLI_EXIT_CODES.policy,
  IDENTITY_PROBE_UNSUPPORTED: CLI_EXIT_CODES.policy,
  IDENTITY_VERIFICATION_FAILED: CLI_EXIT_CODES.policy,
  OAUTH_RESOURCE_INVALID: CLI_EXIT_CODES.config,
  OAUTH_CONNECTION_INVALID: CLI_EXIT_CODES.config,
  OAUTH_CONNECTION_TARGET_REQUIRED: CLI_EXIT_CODES.config,
  OAUTH_CONNECTION_NOT_FOUND: CLI_EXIT_CODES.config,
  OAUTH_CONNECTION_BINDING_MISMATCH: CLI_EXIT_CODES.config,
  OAUTH_CONNECTION_STORE_UNAVAILABLE: CLI_EXIT_CODES.config,
  OAUTH_SECURE_STORE_UNAVAILABLE: CLI_EXIT_CODES.secret,
  OAUTH_CREDENTIAL_NOT_FOUND: CLI_EXIT_CODES.secret,
  OAUTH_CREDENTIAL_INVALID: CLI_EXIT_CODES.secret,
  OAUTH_REFRESH_TIMEOUT: CLI_EXIT_CODES.secret,
  OAUTH_REFRESH_CANCELLED: CLI_EXIT_CODES.secret,
  OAUTH_REAUTH_REQUIRED: CLI_EXIT_CODES.secret,
  OAUTH_DISCOVERY_UNSUPPORTED: CLI_EXIT_CODES.upstream,
  OAUTH_CLIENT_REGISTRATION_UNSUPPORTED: CLI_EXIT_CODES.upstream,
  OAUTH_AUTHORIZATION_FAILED: CLI_EXIT_CODES.secret,
  OAUTH_INTERACTIVE_REQUIRED: CLI_EXIT_CODES.config,
  OAUTH_AUTHORIZATION_NOT_ENABLED: CLI_EXIT_CODES.config,
  CONSOLE_LAUNCHER_UNAVAILABLE: CLI_EXIT_CODES.operation,
  CONSOLE_CONFIGURATION_NOT_FOUND: CLI_EXIT_CODES.config,
  CONSOLE_CONFIGURATION_SELECTION_REQUIRED: CLI_EXIT_CODES.config,
  CONSOLE_CONFIG_DISCOVERY_UNAVAILABLE: CLI_EXIT_CODES.operation,
  TOOL_COLLISION: CLI_EXIT_CODES.operation,
  TOOL_NOT_FOUND: CLI_EXIT_CODES.operation,
  TOOL_SCHEMA_MISMATCH: CLI_EXIT_CODES.operation,
  RESOURCE_COLLISION: CLI_EXIT_CODES.operation,
  RESOURCE_NOT_FOUND: CLI_EXIT_CODES.operation,
  RESOURCE_CURSOR_INVALID: CLI_EXIT_CODES.operation,
  RESOURCE_DISCOVERY_INVALIDATED: CLI_EXIT_CODES.operation,
  RESOURCE_TEMPLATE_COLLISION: CLI_EXIT_CODES.operation,
  RESOURCE_TEMPLATE_CURSOR_INVALID: CLI_EXIT_CODES.operation,
  RESOURCE_TEMPLATE_DISCOVERY_INVALIDATED: CLI_EXIT_CODES.operation,
  RESOURCE_TEMPLATE_UNSUPPORTED: CLI_EXIT_CODES.operation,
  RESOURCE_TEMPLATES_UNAVAILABLE: CLI_EXIT_CODES.operation,
  RESOURCE_SUBSCRIPTION_NOT_FOUND: CLI_EXIT_CODES.operation,
  RESOURCE_SUBSCRIPTION_UNSUPPORTED: CLI_EXIT_CODES.operation,
  PROMPT_COLLISION: CLI_EXIT_CODES.operation,
  PROMPT_NOT_FOUND: CLI_EXIT_CODES.operation,
  PROMPT_CURSOR_INVALID: CLI_EXIT_CODES.operation,
  PROMPT_DISCOVERY_INVALIDATED: CLI_EXIT_CODES.operation
};

describe("CLI exit-code mapping", () => {
  it("maps every declared Miftah error code explicitly", () => {
    expect(ERROR_EXIT_CODES).toEqual(expectedErrorExitCodes);
  });

  it("keeps configuration diagnostic collisions distinct from runtime policy and upstream failures", () => {
    expect(ERROR_EXIT_CODES.POLICY_NOT_FOUND).toBe(CLI_EXIT_CODES.config);
    expect(ERROR_EXIT_CODES.POLICY_BLOCKED).toBe(CLI_EXIT_CODES.policy);
    expect(ERROR_EXIT_CODES.UPSTREAM_NOT_FOUND).toBe(CLI_EXIT_CODES.config);
    expect(ERROR_EXIT_CODES.UPSTREAM_START_FAILED).toBe(CLI_EXIT_CODES.upstream);
    expect(ERROR_EXIT_CODES.UPSTREAM_SELECTION_AMBIGUOUS).toBe(CLI_EXIT_CODES.upstream);
    expect(ERROR_EXIT_CODES.ROUTING_PROFILE_NOT_FOUND).toBe(CLI_EXIT_CODES.config);
    expect(ERROR_EXIT_CODES.ROUTING_BLOCKED).toBe(CLI_EXIT_CODES.policy);
  });

  it("maps usage and unclassified errors without changing their output handling", () => {
    expect(exitCodeForError(new CliUsageError("invalid command line"))).toBe(CLI_EXIT_CODES.usage);
    expect(exitCodeForError(new MiftahError("SECRET_ENV_MISSING", "missing secret"))).toBe(CLI_EXIT_CODES.secret);
    expect(exitCodeForError(new Error("unexpected failure"))).toBe(CLI_EXIT_CODES.operation);
  });
});
