import type { MiftahErrorCode } from "../utils/errors.js";
import { MiftahError } from "../utils/errors.js";
import { CliUsageError } from "./parse.js";

export const CLI_EXIT_CODES = {
  success: 0,
  operation: 1,
  usage: 2,
  config: 3,
  secret: 4,
  upstream: 5,
  policy: 6
} as const;

export type CliExitCode = (typeof CLI_EXIT_CODES)[keyof typeof CLI_EXIT_CODES];

export const ERROR_EXIT_CODES = {
  CONFIG_NOT_FOUND: CLI_EXIT_CODES.config,
  CONFIG_INVALID_JSON: CLI_EXIT_CODES.config,
  CONFIG_SCHEMA_INVALID: CLI_EXIT_CODES.config,
  CONFIG_UNKNOWN_OPTION: CLI_EXIT_CODES.config,
  UNSUPPORTED_CONFIG_VERSION: CLI_EXIT_CODES.config,
  DEFAULT_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  POLICY_NOT_FOUND: CLI_EXIT_CODES.config,
  ROUTING_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  LOCK_PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  UPSTREAM_NOT_FOUND: CLI_EXIT_CODES.config,
  UNSUPPORTED_CONFIG_OPTION: CLI_EXIT_CODES.config,
  PROFILE_NOT_FOUND: CLI_EXIT_CODES.config,
  PROFILE_SWITCH_DISABLED: CLI_EXIT_CODES.config,
  PROFILE_SWITCH_CONFIRMATION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_SELECTION_STALE: CLI_EXIT_CODES.policy,
  PROFILE_LOCKING_DISABLED: CLI_EXIT_CODES.policy,
  PROFILE_LOCKED: CLI_EXIT_CODES.policy,
  PROFILE_LEASE_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_LEASE_EXPIRED: CLI_EXIT_CODES.policy,
  PROFILE_SELECTION_REQUIRED: CLI_EXIT_CODES.policy,
  PROFILE_STATE_WRITE_FAILED: CLI_EXIT_CODES.config,
  SECRET_ENV_MISSING: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_FAILED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_UNAVAILABLE: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_TIMEOUT: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_CANCELLED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_LOCKED: CLI_EXIT_CODES.secret,
  SECRET_PROVIDER_NONINTERACTIVE: CLI_EXIT_CODES.secret,
  SECRET_REFERENCE_MALFORMED: CLI_EXIT_CODES.secret,
  SECRET_ITEM_MISSING: CLI_EXIT_CODES.secret,
  UPSTREAM_START_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_INIT_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_SHUTDOWN_TIMEOUT: CLI_EXIT_CODES.upstream,
  UPSTREAM_CONCURRENCY_LIMIT: CLI_EXIT_CODES.upstream,
  UPSTREAM_RESTART_LIMIT_EXCEEDED: CLI_EXIT_CODES.upstream,
  UPSTREAM_TOOL_LIST_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_DISCOVERY_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_CALL_FAILED: CLI_EXIT_CODES.upstream,
  UPSTREAM_HTTP_ERROR: CLI_EXIT_CODES.upstream,
  UPSTREAM_PROTOCOL_ERROR: CLI_EXIT_CODES.upstream,
  AUDIT_WRITE_FAILED: CLI_EXIT_CODES.operation,
  UPSTREAM_SELECTION_AMBIGUOUS: CLI_EXIT_CODES.upstream,
  ROUTING_AMBIGUOUS: CLI_EXIT_CODES.policy,
  ROUTING_BLOCKED: CLI_EXIT_CODES.policy,
  POLICY_BLOCKED: CLI_EXIT_CODES.policy,
  POLICY_CONFIRMATION_REQUIRED: CLI_EXIT_CODES.policy,
  APPROVAL_INVALID: CLI_EXIT_CODES.policy,
  APPROVAL_EXPIRED: CLI_EXIT_CODES.policy,
  APPROVAL_NOT_PENDING: CLI_EXIT_CODES.policy,
  APPROVAL_LIMIT_EXCEEDED: CLI_EXIT_CODES.policy,
  IDENTITY_NOT_CONFIGURED: CLI_EXIT_CODES.policy,
  IDENTITY_MISMATCH: CLI_EXIT_CODES.policy,
  IDENTITY_PROBE_UNSUPPORTED: CLI_EXIT_CODES.policy,
  IDENTITY_VERIFICATION_FAILED: CLI_EXIT_CODES.policy,
  TOOL_COLLISION: CLI_EXIT_CODES.operation,
  TOOL_NOT_FOUND: CLI_EXIT_CODES.operation,
  TOOL_SCHEMA_MISMATCH: CLI_EXIT_CODES.operation,
  RESOURCE_COLLISION: CLI_EXIT_CODES.operation,
  RESOURCE_NOT_FOUND: CLI_EXIT_CODES.operation,
  RESOURCE_CURSOR_INVALID: CLI_EXIT_CODES.operation,
  RESOURCE_DISCOVERY_INVALIDATED: CLI_EXIT_CODES.operation,
  PROMPT_COLLISION: CLI_EXIT_CODES.operation,
  PROMPT_NOT_FOUND: CLI_EXIT_CODES.operation,
  PROMPT_CURSOR_INVALID: CLI_EXIT_CODES.operation,
  PROMPT_DISCOVERY_INVALIDATED: CLI_EXIT_CODES.operation
} satisfies Record<MiftahErrorCode, CliExitCode>;

export function exitCodeForError(error: unknown): CliExitCode {
  if (error instanceof CliUsageError) return CLI_EXIT_CODES.usage;
  if (error instanceof MiftahError) return ERROR_EXIT_CODES[error.code];
  return CLI_EXIT_CODES.operation;
}
